#!/usr/bin/python
import subprocess
import string
import os

#open template file
charm_dir = os.environ['CHARM_DIR']
with open( '%s/lib/source_template.txt' % charm_dir ) as f:
        src = string.Template( f.read() )

d = {}

repo_server = subprocess.check_output(["config-get", "repo"], stderr=subprocess.STDOUT)
d['REPO'] = repo_server.rstrip()

result = src.substitute(d)
with open("/etc/apt/sources.list.d/clearwater.list", 'w') as f:
        f.write(result)
