#!/bin/bash

# Update the config file
mkdir /etc/clearwater/
touch /etc/clearwater/config
$CHARM_DIR/lib/config_script
chmod 755 /etc/clearwater/config

# Restart clearwater-infrastructure
service clearwater-infrastructure restart
service sprout stop
