#!/bin/bash
set -e

# Set our DNS requirements
relation-set domain=$(config-get zone)
relation-set resources='sprout IN A '$(unit-get public-address)'
sprout IN NAPTR 1 1 "S" "SIP+D2T" "" _sip._tcp.sprout
_sip._tcp.sprout IN SRV 0 0 5054 sprout-$id
sprout-$id IN A '$(unit-get public-address)

# Update our DNS server
echo nameserver $(relation-get public-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
