#!/bin/bash

peer_ip=`relation-get private-address`
this_ip=`unit-get private-address`

peer_index=$(echo $JUJU_REMOTE_UNIT | cut -d'/' -f2)
this_index=$(echo $JUJU_UNIT_NAME | cut -d'/' -f2)

# Mark the new node as joining
if [ $this_index -gt $peer_index ]
  then
    $CHARM_DIR/lib/node_script "$peer_ip" "$peer_index" "True" "False" 
    $CHARM_DIR/lib/node_script "$this_ip" "$this_index" "True" "True"
  else
    $CHARM_DIR/lib/node_script "$peer_ip" "$peer_index" "True" "True"
    $CHARM_DIR/lib/node_script "$this_ip" "$this_index" "True" "False"
fi

$CHARM_DIR/lib/basic_node_script "True"

chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json
