#!/bin/bash
set -e

# Only does something if we're in the middle of scaling up
if ! grep -q "new_servers" /etc/clearwater/cluster_settings; then
  exit 0
fi

# If there's already a deferred timer running, stop it
JOB_FILE=$CHARM_DIR/lib/cluster_timer.job
if [[ -f $JOB_FILE ]] && atq | grep -q -P "^$(cat $JOB_FILE)\t"; then
  atrm $(cat $JOB_FILE) 2>&1 > /dev/null || true
fi

# Restart the timer (set for 6 minutes time since 'at' rounds down)
at -f $CHARM_DIR/lib/finish_scale now + 6 minutes 2>&1 | grep -v warning | cut -d' ' -f 2 > $JOB_FILE
