#!/bin/bash
public_ip=`curl http://169.254.169.254/latest/meta-data/public-ipv4`
relation-set public-address=$public_ip

# Update the source list with the correct repo server
touch /etc/apt/sources.list.d/clearwater.list
chmod 777 /etc/apt/sources.list.d/clearwater.list
$CHARM_DIR/lib/source_script
chmod 644 /etc/apt/sources.list.d/clearwater.list

# Update the config file
mkdir /etc/clearwater/
touch /etc/clearwater/config
$CHARM_DIR/lib/config_script
chmod 755 /etc/clearwater/config
