#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
set -e

# This hook needs to be idempotent, so this could be run when
# clearwater-sip-stress is already running.  As a result, we should always
# restart it.
service clearwater-sip-stress restart
