#!/bin/bash
public_ip=`curl http://169.254.169.254/latest/meta-data/public-ipv4`
relation-set public-address=$public_ip

# Update the config file
$CHARM_DIR/lib/config_script

# Restart clearwater-infrastructure
service clearwater-infrastructure restart
service bono stop
