#!/bin/bash

# This covers installing chef-solo and the Clearwater chef recipes
# Install needed libraries 
apt-get -y install git libxml2-dev libxslt1-dev wget curl

# Install chef
install_sh="http://opscode.com/chef/install.sh"
version_string="-v 11.6.0"
bash <(wget  ${install_sh} -O -) ${version_string}

# Pull down the Clearwater chef recipes
if [ ! -d /home/ubuntu/chef-solo ]
  then
  mkdir /home/ubuntu/chef-solo
  git clone -b master git://github.com/Metaswitch/chef.git /home/ubuntu/chef-solo
fi

# Update the chef recipes
cd /home/ubuntu/chef-solo
git pull origin master
git submodule update --init
