#!/usr/bin/python
import subprocess
import string
import socket
import os
import urllib2 

#open template file
charm_dir = os.environ['CHARM_DIR']
with open( '%s/lib/config_template.txt' % charm_dir ) as f:
	src = string.Template( f.read() )

d = {}

local_hostname = subprocess.check_output(["unit-get", "private-address"], stderr=subprocess.STDOUT)
public_hostname = subprocess.check_output(["unit-get", "public-address"], stderr=subprocess.STDOUT)
local_ip = socket.gethostbyname(local_hostname.rstrip())
response = urllib2.urlopen('http://169.254.169.254/latest/meta-data/public-ipv4')
public_ip = response.read()

try:
        home_domain = subprocess.check_output(["relation-get", "home_domain"], stderr=subprocess.STDOUT)
        sprout_domain = subprocess.check_output(["relation-get", "sprout_domain"], stderr=subprocess.STDOUT)
        hs_domain = subprocess.check_output(["relation-get", "homestead_domain"], stderr=subprocess.STDOUT)
        hs_prov_domain = subprocess.check_output(["relation-get", "provisioning_domain"], stderr=subprocess.STDOUT)
        xdms_domain = subprocess.check_output(["relation-get", "homer_domain"], stderr=subprocess.STDOUT)
        ralf_domain = subprocess.check_output(["relation-get", "ralf_domain"], stderr=subprocess.STDOUT)
        sas_domain = subprocess.check_output(["relation-get", "sas_domain"], stderr=subprocess.STDOUT)
        enum_domain = subprocess.check_output(["relation-get", "enum_domain"], stderr=subprocess.STDOUT)
except subprocess.CalledProcessError:
        home_domain = "localhost"
        sprout_domain = "localhost"
        hs_domain = "localhost:8888"
        hs_prov_domain = "localhost:8889"
        xdms_domain = "localhost:7888"
        ralf_domain = "localhost:9888"
        sas_domain = "0.0.0.0"
        enum_domain = ""

# populate dictionary
d['LOCAL_IP'] = local_ip.rstrip()
d['PUBLIC_IP'] = public_ip.rstrip()
d['PUBLIC_HOSTNAME'] = public_hostname.rstrip()

d['HOME_DOMAIN'] = home_domain or "localhost"
d['SPROUT_HOSTNAME'] = sprout_domain or "localhost"
d['HS_HOSTNAME'] = hs_domain or "localhost:8888"
d['HS_PROVISIONING_HOSTNAME'] = hs_prov_domain or "localhost:8889"
d['XDMS_HOSTNAME'] = xdms_domain or "localhost:7888"
d['RALF_HOSTNAME'] = ralf_domain or "localhost:9888"
d['SAS_SERVER'] = sas_domain or "0.0.0.0"

if enum_domain:
        d['ENUM_SERVER'] = "enum_server=" + enum_domain.rstrip()
else:
        d['ENUM_SERVER'] = ""

result = src.substitute(d)
with open("/etc/clearwater/config", 'w') as f:
	f.write(result)
