#!/bin/bash

# Update the config file
mkdir /etc/clearwater/
touch /etc/clearwater/config
$CHARM_DIR/lib/config_script
chmod 755 /etc/clearwater/config

$CHARM_DIR/lib/basic_node_script
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json

# Restart clearwater-infrastructure
service clearwater-infrastructure restart
service bono stop
