#!/bin/bash

# Install chef solo
$CHARM_DIR/lib/chef_solo_install
# Create the solo.rb file
$CHARM_DIR/lib/create_solo_file

$CHARM_DIR/lib/basic_node_script

# Update the config file
mkdir /etc/clearwater/
touch /etc/clearwater/config
$CHARM_DIR/lib/config_script
chmod 755 /etc/clearwater/config

apt-get update

# Install the node
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json

# Expose the correct ports
open-port 22/tcp
open-port 123/udp
open-port 161/udp
open-port 3478/tcp
open-port 3478/udp
open-port 5060/tcp
open-port 5060/udp
open-port 5062/tcp
open-port 6666/tcp
# open-port doesn't currently support ranges
#open-port 32768-65535/udp
