#!/bin/bash
set -e

# This is a big hack.  Juju on EC2 returns hostnames rather than IP addresses
# for public-address and private-address.  To work-around this, we resolve the
# host names.  However, after we've joined to the DNSaaS charm, we can no longer
# resolve these, so add them to /etc/hosts.
if ! grep "# added by clearwater-*/hooks/install" /etc/hosts ; then
  cat >>/etc/hosts <<EOF
$(dig +short $(unit-get private-address) | head -1) $(unit-get private-address) # added by clearwater-*/hooks/install
$(dig +short $(unit-get public-address) | head -1) $(unit-get public-address) bono-$(cut -d/ -f2 <<< $JUJU_UNIT_NAME).$(config-get zone) # added by clearwater-*/hooks/install
EOF
fi

# Install chef solo, and create the node.json and config file
$CHARM_DIR/lib/chef_solo_install
$CHARM_DIR/lib/node_json_script
$CHARM_DIR/lib/config_script

apt-get update

# Install the node
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json

# Expose the correct ports
open-port 22/tcp
open-port 123/udp
open-port 161/udp
open-port 3478/tcp
open-port 3478/udp
open-port 5060/tcp
open-port 5060/udp
open-port 5062/tcp
open-port 6666/tcp
