#!/bin/bash
set -e

# Set our DNS requirements
relation-set domain=$(config-get zone)
relation-set resources='@ IN A '$(unit-get public-address)'
@ IN NAPTR 1 1 "S" "SIP+D2T" "" _sip._tcp
@ IN NAPTR 2 1 "S" "SIP+D2U" "" _sip._udp
_sip._tcp IN SRV 0 0 5060 bono-$id
_sip._udp IN SRV 0 0 5060 bono-$id
bono-$id IN A '$(unit-get public-address)

# Update our DNS server
echo nameserver $(relation-get public-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

# Update Clearwater configuration
$CHARM_DIR/lib/config_script programmable-multiple

# Restart clearwater-infrastructure, and stop bono (to be restarted by monit)
service clearwater-infrastructure restart
service bono stop
