#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
service monit stop
service homestead start
service monit start
sleep 1
monit monitor homestead
