#!/bin/bash

# Install chef solo
$CHARM_DIR/lib/chef_solo_install
# Create the solo.rb file
$CHARM_DIR/lib/create_solo_file

this_ip=`unit-get private-address`
this_index=$(echo $JUJU_UNIT_NAME | cut -d'/' -f2)

$CHARM_DIR/lib/node_script "$this_ip" "$this_index" "False" "False"
$CHARM_DIR/lib/basic_node_script "False"

# Update the config file
mkdir /etc/clearwater/
touch /etc/clearwater/config
$CHARM_DIR/lib/config_script
chmod 755 /etc/clearwater/config

apt-get update

# Install the node
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json

# Expose the correct ports
open-port 22/tcp
open-port 123/udp
open-port 161/udp
