#!/bin/bash
set -e

# Set our DNS requirements
TTL=300
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(dig +short $(unit-get private-address) | head -1)
relation-set domain=$(config-get zone)
relation-set resources='homer '$TTL' IN A '$ip'
homer-'$id' '$TTL' IN A '$ip

# Update our DNS server
[ "$(relation-get public-address)" = "" ] || echo nameserver $(relation-get public-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
