#!/bin/bash

# This is a big hack.  Juju on EC2 returns hostnames rather than IP addresses
# for public-address and private-address.  To work-around this, we resolve the
# host names.  However, after we've joined to the DNSaaS charm, we can no longer
# resolve these, so add them to /etc/hosts.
if ! grep "# added by clearwater-*/hooks/install" /etc/hosts ; then
  cat >>/etc/hosts <<EOF
$(dig +short $(unit-get private-address) | head -1) $(unit-get private-address) # added by clearwater-*/hooks/install
$(dig +short $(unit-get public-address) | head -1) $(unit-get public-address) ellis-$(cut -d/ -f2 <<< $JUJU_UNIT_NAME).$(config-get zone) # added by clearwater-*/hooks/install
EOF
fi

# Install chef solo, and create the node.json and config file
$CHARM_DIR/lib/chef_solo_install
$CHARM_DIR/lib/node_json_script
$CHARM_DIR/lib/config_script

apt-get update

# Install the node
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json

# Create subscribers
/usr/share/clearwater/ellis/env/bin/python /usr/share/clearwater/ellis/src/metaswitch/ellis/tools/create_numbers.py --start "$(config-get base_number)" --count "$(config-get number_count)"

# Expose the correct ports
open-port 22/tcp
open-port 80/tcp
open-port 123/udp
open-port 161/udp
open-port 443/tcp
