#!/bin/bash

# Install chef solo, and create the node.json and config file
$CHARM_DIR/lib/chef_solo_install
$CHARM_DIR/lib/node_json_script
$CHARM_DIR/lib/config_script

apt-get update

# Install the node
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json

# Create subscribers
/usr/share/clearwater/ellis/env/bin/python /usr/share/clearwater/ellis/src/metaswitch/ellis/tools/create_numbers.py --start "$(config-get base_number)" --count "$(config-get number_count)"

# Expose the correct ports
open-port 22/tcp
open-port 80/tcp
open-port 123/udp
open-port 161/udp
open-port 443/tcp
