#!/bin/bash
set -e

# Set our DNS requirements
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
relation-set domain=$(config-get zone)
relation-set resources='ellis IN A '$ip'
ellis-'$id' IN A '$ip

# Update our DNS server
[ "$(relation-get public-address)" = "" ] || echo nameserver $(relation-get public-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
