#!/bin/bash
set -e

# Set our DNS requirements
TTL=300
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
relation-set domain=$(config-get zone)
relation-set resources='ellis '$TTL' IN A '$ip'
ellis-'$id' '$TTL' IN A '$ip

# Update our DNS server
if [ "$(relation-get public-address)" != "" ]
then
  echo nameserver $(relation-get public-address) > /etc/dnsmasq.resolv.conf
  grep -v ^RESOLV_CONF= /etc/default/dnsmasq > /tmp/dnsmasq.$$
  mv /tmp/dnsmasq.$$ /etc/default/dnsmasq
  echo RESOLV_CONF=/etc/dnsmasq.resolv.conf > /etc/default/dnsmasq
  service dnsmasq restart
fi

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
