#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
set -e

# This hook needs to be idempotent, so this could be run when ellis is
# already running, when it's running but not monitored by monit, when
# it's stopped but being monitored (so it's about to start), or stopped
# and unmonitored. To cover all these cases, stop monit, start ellis, start
# monit, then finally have monit monitor ellis
service monit stop
service ellis start
service monit start
sleep 1
monit monitor ellis
