#!/bin/bash

apt-get install -y ruby1.9.3 build-essential libxslt1-dev
gem install aws-sdk --no-ri --no-rdoc

ruby lib/clean.rb --access_key `config-get access_key` \
                  --secret_key `config-get secret_key` \
                  --zone `config-get zone`
