#!/bin/bash

set -e

peer_ip=`relation-get public-address`
root_zone=`config-get zone`

if [[ -z $peer_ip ]]
then
  juju-log "Peer disconnected but has no IP address"
  exit 0;
fi

juju-log "Lost a bono node: $peer_ip"

ruby $CHARM_DIR/lib/remove_address.rb --access-key `config-get access_key` \
                                      --secret-key `config-get secret_key` \
                                      --zone `config-get zone`             \
                                      --role bono                          \
                                      --address $peer_ip

$CHARM_DIR/lib/declare_domains.sh $root_zone
