#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)
set -e

zone=$(config-get zone)
public_ip=$(dig +short $(unit-get public-address) | head -1)

cat >/etc/bind/named.conf.local <<EOF
zone "$zone" {
  type master;
  file "/etc/bind/db.$zone";
};
EOF

cat >/etc/bind/db.$zone.prefix <<EOF
\$TTL 5m ; Default TTL

; SOA, NS and A record for DNS server itself
@ 3600 IN SOA ns admin ( 2014010800 3600 3600 3600 300 )
@ 3600 IN NS ns
ns 3600 IN A $public_ip ; IPv4 address of BIND server
EOF

cat /etc/bind/db.$zone.prefix >/etc/bind/db.$zone
[ "$(ls /etc/bind/db.$zone.unit* 2>/dev/null)" = "" ] || cat /etc/bind/db.$zone.unit* >>/etc/bind/db.$zone
service bind9 reload
