#!/bin/bash

set -e

zone=$(config-get zone)
id=$(cut -d/ -f2 <<< $JUJU_REMOTE_UNIT)

rm -f /etc/bind/db.$zone.unit$id

cat /etc/bind/db.$zone.prefix >/etc/bind/db.$zone
[ "$(ls /etc/bind/db.$zone.unit* 2>/dev/null)" = "" ] || cat /etc/bind/db.$zone.unit* >>/etc/bind/db.$zone
service bind9 reload
