#!/bin/bash

set -e

zone=$(config-get zone)
id=$(cut -d/ -f2 <<< $JUJU_REMOTE_UNIT)
ip=$(relation-get private-address)

$CHARM_DIR/lib/declare_domains.sh $zone

cat >/etc/bind/db.$zone.unit$id <<EOF
sprout IN A $ip
sprout IN NAPTR 1 1 "S" "SIP+D2T" "" _sip._tcp.sprout
_sip._tcp.sprout IN SRV 0 0 5054 sprout-$id
sprout-$id IN A $ip
EOF

cat /etc/bind/db.$zone.prefix >/etc/bind/db.$zone
[ "$(ls /etc/bind/db.$zone.unit* 2>/dev/null)" = "" ] || cat /etc/bind/db.$zone.unit* >>/etc/bind/db.$zone
service bind9 reload
