#!/bin/bash

set -e

zone=$(config-get zone)
id=$(cut -d/ -f2 <<< $JUJU_REMOTE_UNIT)
ip=$(relation-get public-address)

$CHARM_DIR/lib/declare_domains.sh $zone

cat >/etc/bind/db.$zone.unit$id <<EOF
@ IN A $ip
@ IN NAPTR 1 1 "S" "SIP+D2T" "" _sip._tcp
@ IN NAPTR 2 1 "S" "SIP+D2U" "" _sip._udp
_sip._tcp IN SRV 0 0 5060 bono-$id
_sip._udp IN SRV 0 0 5060 bono-$id
bono-$id IN A $ip
EOF

cat /etc/bind/db.$zone.prefix >/etc/bind/db.$zone
[ "$(ls /etc/bind/db.$zone.unit* 2>/dev/null)" = "" ] || cat /etc/bind/db.$zone.unit* >>/etc/bind/db.$zone
service bind9 reload
