#!/bin/bash
set -e

# Set our DNS requirements
relation-set domain=$(config-get zone)
relation-set resources='homestead IN A '$(unit-get public-address)'
homestead-$id IN A '$(unit-get public-address)

# Update our DNS server
echo nameserver $(relation-get public-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
