#!/usr/bin/python

import subprocess
import string
import os
import sys

# Open template file
charm_dir = os.environ['CHARM_DIR']
with open( '%s/lib/basic_node_template.txt' % charm_dir ) as f:
        src = string.Template( f.read() )

d = {}

repo_server = subprocess.check_output(["config-get", "repo"], stderr=subprocess.STDOUT)

# Populate dictionary
d['REPO'] = repo_server.rstrip()

result = src.substitute(d)

with open('/home/ubuntu/chef-solo/node.json', 'w') as f:
        f.write(result)
