#!/usr/bin/python
import subprocess
import string
import socket
import os
import urllib2
import random

# Create the /etc/clearwater/config file.
#
# Node specific information is got from the charms config, the IP
# infomation is got from the unit config, and the domain information
# is got from the relation with the clearwater-route53 charm
#
# The config file is templated in lib/config_template.

# Populate the dictionary
d = {}

# Ellis specific config
d['SMTP_SMARTHOST'] = subprocess.check_output(["config-get", "smtp_server"])
d['SMTP_USERNAME'] = subprocess.check_output(["config-get", "smtp_username"])
d['SMTP_PASSWORD'] = subprocess.check_output(["config-get", "smtp_password"])
d['EMAIL_RECOVERY_SENDER'] = subprocess.check_output(["config-get", "email_sender"])
d['SIGNUP_KEY'] = subprocess.check_output(["config-get", "signup_key"])
d['COOKIE_KEY'] = "secret"
d['API_KEY'] = "%030x" % random.randrange(16**30)

# IP configuration
d['PUBLIC_HOSTNAME'] = subprocess.check_output(["unit-get", "public-address"])
d['LOCAL_IP'] = socket.gethostbyname(subprocess.check_output(["unit-get", "private-address"]).rstrip())
d['PUBLIC_IP'] = urllib2.urlopen('http://169.254.169.254/latest/meta-data/public-ipv4').read()

# Domain configuration
try:
        d['HOME_DOMAIN'] = subprocess.check_output(["relation-get", "home_domain"]).rstrip()
        d['SPROUT_HOSTNAME'] = subprocess.check_output(["relation-get", "sprout_domain"]).rstrip()
        d['HS_HOSTNAME'] = subprocess.check_output(["relation-get", "homestead_domain"]).rstrip()
        d['HS_PROVISIONING_HOSTNAME'] = subprocess.check_output(["relation-get", "provisioning_domain"]).rstrip()
        d['XDMS_HOSTNAME'] = subprocess.check_output(["relation-get", "homer_domain"]).rstrip()
        d['RALF_HOSTNAME'] = subprocess.check_output(["relation-get", "ralf_domain"]).rstrip()
        d['SAS_SERVER'] = subprocess.check_output(["relation-get", "sas_domain"]).rstrip()
        d['ENUM_SERVER'] = "enum_server=" + subprocess.check_output(["relation-get", "enum_domain"]).rstrip()
except subprocess.CalledProcessError:
        d['HOME_DOMAIN'] = "localhost"
        d['SPROUT_HOSTNAME'] = "localhost"
        d['HS_HOSTNAME'] = "localhost:8888"
        d['HS_PROVISIONING_HOSTNAME'] = "localhost:8889"
        d['XDMS_HOSTNAME'] = "localhost:7888"
        d['RALF_HOSTNAME'] = "localhost:9888"
        d['SAS_SERVER'] = "0.0.0.0"
        d['ENUM_SERVER'] = ""

# Open the template file
charm_dir = os.environ['CHARM_DIR']
with open( '%s/lib/config_template' % charm_dir ) as f:
        src = string.Template( f.read() )

# Make the substitutions
result = src.substitute(d)

# Write to /etc/clearwater/config, creating the clearwater directory
# if necessary, and set appropriate permissions
if not os.path.isdir("/etc/clearwater"):
        os.makedirs("/etc/clearwater")
with open("/etc/clearwater/config", 'w') as f:
	f.write(result)
os.chmod("/etc/clearwater/config", 0755)
