#!/bin/bash
public_ip=`curl http://169.254.169.254/latest/meta-data/public-ipv4`
relation-set public-address=$public_ip

# Update the config file
$CHARM_DIR/lib/config_script

# Restart clearwater-infrastructure
service clearwater-infrastructure restart
service ellis stop

home_domain=`relation-get home_domain`
if [[ -n $home_domain ]]
then
  /usr/share/clearwater/ellis/env/bin/python /usr/share/clearwater/ellis/src/metaswitch/ellis/tools/create_numbers.py --start "$(config-get base_number)" --count "$(config-get number_count)"
fi
