#!/bin/bash
set -e

key=$1
val=$(unit-get $1)

if [ "$key" = "public-address" ] &&
   [ -n "$(dig +short $val | head -1)" ]
then
  val=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
elif [ "$key" = "private-address" ]
then
  val_ip=$(dig +short $val | head -1)
  [ -z "$val_ip" ] || val=$val_ip
fi

echo $val
