#!/usr/bin/python
import subprocess
import string
import os

#open template file
charm_dir = os.environ['CHARM_DIR']
with open( '%s/lib/config_template.txt' % charm_dir ) as f:
	src = string.Template( f.read() )

d = {}

turn_password = subprocess.check_output(["config-get", "turn_password"], stderr=subprocess.STDOUT)
#homestead_domain = subprocess.check_output(["config-get", "homestead_domain"])
#sprout_domain = subprocess.check_output(["config-get", "sprout_domain"])

# populate dictionary
#d[REPO] = repo
d['TURN_PASSWORD'] = turn_password
#d[HOMESTEAD_DOMAIN] = homestead_domain
#d[SPROUT_DOMAIN] = sprout_domain
#d[HOMER_DOMAIN] = homer_domain
#d[ELLIS_DOMAIN] = ellis_domain
#d[RALF_DOMAIN] = ralf_domain
#d[HOME_DOMAIN] = home_domain
#d[SAS_DOMAIN] = sas_domain
#d[ENUM_DOMAIN] = enum_domain

result = src.substitute(d)
#out = open("/etc/clearwater/config", 'w')
with open("/etc/clearwater/config", 'w') as f:
	f.write(result)
#sudo cat > /etc/clearwater/config << result

