#!/bin/bash

$relation_name=$1

set -e

# Defaults
sprout_hostname=sprout.$(config-get zone)
hs_hostname=homestead.$(config-get zone):8888
hs_provisioning_hostname=homestead.$(config-get zone):8889
xdms_hostname=homer.$(config-get zone):7888
ralf_hostname=
sas_server=0.0.0.0
enum_server=

# Import existing configuration
[ ! -f /etc/clearwater/config ] || . /etc/clearwater/config

# Apply new configuration
home_domain=$(config-get zone)
sas_server=$(config-get sas)
local_ip=$(dig +short $(unit-get private-address) | head -1)
public_ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
public_hostname=$(unit-get public-address)

# Write configuration back
mkdir -p /etc/clearwater
cat >/etc/clearwater/config <<EOF
# Deployment definitions
home_domain=$home_domain
sprout_hostname=$sprout_hostname
hs_hostname=$hs_hostname
hs_provisioning_hostname=$hs_provisioning_hostname
xdms_hostname=$xdms_hostname
ralf_hostname=$ralf_hostname
sas_server=$sas_server
enum_server=$enum_server

# Local IP configuration
local_ip=$local_ip
public_ip=$public_ip
public_hostname=$public_hostname
EOF
