#!/bin/bash
set -e

# Clear the joining attribute on all nodes in the cluster
for f in /home/ubuntu/chef-solo/data_bags/node/*.json; do
  sed -i 's/"joining": true/"joining": false/' $f
done

# And re-run chef-solo
chef-solo -c /home/ubuntu/chef-solo/solo.rb -j /home/ubuntu/chef-solo/node.json
